name: Pushing image to docker hub 

on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: building docker image
     
       
   - name: Build and push image
     id: docker_build
     uses: docker/build-push-action@v2
     with:
      context: ./
      file: ./Dockerfile
      push: true
      registry: dockerhub-and-github-actions/mying
     
     
 
 
   
   
  
      
