name: Pushing image to docker hub 

on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: building docker image
     run: docker build ./ -t nodejs 
       
   -  name: Login to DockerHub
   -   uses: docker/login-action@v1 
       with:
         username: ${{ secrets.USERNAME }}
         password: ${{ secrets.PASSWORD }}
    
   - name: Build and push image
     id: docker_build
     uses: docker/build-push-action@v2
     with:
      context: ./
      file: ./Dockerfile
      push: true
      registry: dockerhub-and-github-actions/mying
   
 
 
   
   
  
      
