name: Pushing image to docker hub 

on: push
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: building docker image
     run: |
       docker build ./ -t mying 
   
   
  
      
