name: Docker Image CI

on: push
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2      
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg git_commit=$(git log -1 --format=%h) --tag:pkatwal/github:git_commit
      
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
      
    - name: Docker Push to docker hub 
    - run: docker push pkatwal/github:git_commit
